-- Seed Data for Cloudflare D1
INSERT OR IGNORE INTO Workspace (id, name, ownerId, createdAt) VALUES ('default-workspace', 'My Workspace', NULL, '2026-07-16T20:25:38.529Z');
INSERT OR IGNORE INTO Category (id, workspaceId, name, slug, description, icon, colorAccent, sortOrder) VALUES ('cat-chrome-extension', 'default-workspace', 'Chrome Extension', 'chrome-extension', 'Browser extensions used to improve productivity and daily workflow.', '🌐', '#FF6FB5', 1);
INSERT OR IGNORE INTO Category (id, workspaceId, name, slug, description, icon, colorAccent, sortOrder) VALUES ('cat-vscode-extension', 'default-workspace', 'VS Code Extension', 'vscode-extension', 'Extensions for Visual Studio Code to enhance development experience.', '💎', '#7C6DFF', 2);
INSERT OR IGNORE INTO Category (id, workspaceId, name, slug, description, icon, colorAccent, sortOrder) VALUES ('cat-cursor-extension', 'default-workspace', 'Cursor Extension', 'cursor-extension', 'Extensions, utilities, and tools designed specifically for Cursor IDE.', '✨', '#00C9A7', 3);
INSERT OR IGNORE INTO Category (id, workspaceId, name, slug, description, icon, colorAccent, sortOrder) VALUES ('cat-opencode-extension', 'default-workspace', 'OpenCode Extension', 'opencode-extension', 'Extensions, plugins, and resources related to OpenCode development workflow.', '🔮', '#FF8C42', 4);
INSERT OR IGNORE INTO Category (id, workspaceId, name, slug, description, icon, colorAccent, sortOrder) VALUES ('cat-prompt', 'default-workspace', 'Prompt', 'prompt', 'AI prompts for coding, architecture, automation, design, and productivity.', '💬', '#E879F9', 5);
INSERT OR IGNORE INTO Category (id, workspaceId, name, slug, description, icon, colorAccent, sortOrder) VALUES ('cat-blueprint', 'default-workspace', 'Blueprint', 'blueprint', 'Project blueprints, architecture documents, and technical planning resources.', '📐', '#38BDF8', 6);
INSERT OR IGNORE INTO Category (id, workspaceId, name, slug, description, icon, colorAccent, sortOrder) VALUES ('cat-template', 'default-workspace', 'Template', 'template', 'Reusable project templates, boilerplates, and starter kits for rapid development.', '📋', '#FB923C', 7);
INSERT OR IGNORE INTO Category (id, workspaceId, name, slug, description, icon, colorAccent, sortOrder) VALUES ('cat-script', 'default-workspace', 'Script', 'script', 'Standalone scripts, UserScripts, and utilities for automation and productivity.', '⚡', '#FACC15', 8);
INSERT OR IGNORE INTO Category (id, workspaceId, name, slug, description, icon, colorAccent, sortOrder) VALUES ('cat-automation', 'default-workspace', 'Automation', 'automation', 'Automation tools, workflows, bots, and CI/CD scripts.', '🤖', '#34D399', 9);
INSERT OR IGNORE INTO Category (id, workspaceId, name, slug, description, icon, colorAccent, sortOrder) VALUES ('cat-source-code', 'default-workspace', 'Source Code', 'source-code', 'Complete source code packages, libraries, and reusable code modules.', '🧩', '#F472B6', 10);
INSERT OR IGNORE INTO Category (id, workspaceId, name, slug, description, icon, colorAccent, sortOrder) VALUES ('cat-github-repository', 'default-workspace', 'GitHub Repository', 'github-repository', 'Links and references to GitHub repositories and open-source projects.', '🐙', '#A78BFA', 11);
INSERT OR IGNORE INTO Category (id, workspaceId, name, slug, description, icon, colorAccent, sortOrder) VALUES ('cat-documentation', 'default-workspace', 'Documentation', 'documentation', 'Technical documentation, API references, guides, and how-to articles.', '📚', '#60A5FA', 12);
INSERT OR IGNORE INTO Category (id, workspaceId, name, slug, description, icon, colorAccent, sortOrder) VALUES ('cat-assets', 'default-workspace', 'Assets', 'assets', 'Visual assets, icons, images, stickers, and design resources.', '🎨', '#F87171', 13);
INSERT OR IGNORE INTO Category (id, workspaceId, name, slug, description, icon, colorAccent, sortOrder) VALUES ('cat-learning-resources', 'default-workspace', 'Learning Resources', 'learning-resources', 'Tutorials, courses, articles, and learning materials for developers.', '📖', '#2DD4BF', 14);
INSERT OR IGNORE INTO Resource (id, workspaceId, title, description, sourceType, fileUrl, provider, categoryId, iconEmoji, currentVersion, isFavorite, openCount, downloadCount, createdAt, updatedAt) VALUES ('cmrnykxjo0006c8uqh526g4no', 'default-workspace', 'Pink Password Generator Pro', 'Beautiful pink-themed password generator dashboard for LiveChat agents. Generate secure, unique passwords with a stunning UI. Chrome Extension (Manifest V3).', 'FILE', '/downloads/chrome-extension/Generate-pass-Mila.zip', 'manual', 'cat-chrome-extension', '🔑', '1.0.0', 0, 0, 0, '2026-07-16T20:25:38.772Z', '2026-07-16T20:25:38.772Z');
INSERT OR IGNORE INTO Resource (id, workspaceId, title, description, sourceType, fileUrl, provider, categoryId, iconEmoji, currentVersion, isFavorite, openCount, downloadCount, createdAt, updatedAt) VALUES ('cmrnykxl1000dc8uq4682i5h1', 'default-workspace', 'CS Advanced Tool v2.1 (Otoscatter)', 'Advanced automation tool for LiveChat agents. Features: auto TS, browser-profile independent operation, fast performance. Chrome Extension (Manifest V3).', 'FILE', '/downloads/chrome-extension/CS-Advanced-Tool-v2.1.zip', 'manual', 'cat-chrome-extension', '⚡', '2.1', 0, 0, 0, '2026-07-16T20:25:38.822Z', '2026-07-16T20:25:38.822Z');
INSERT OR IGNORE INTO Resource (id, workspaceId, title, description, sourceType, fileUrl, provider, categoryId, iconEmoji, currentVersion, isFavorite, openCount, downloadCount, createdAt, updatedAt) VALUES ('cmrnykxmg000kc8uqysx1s9aq', 'default-workspace', 'Extension Mila Suite', 'Complete Mila extension suite package containing all Highlighter Pro scripts, decorative assets, and the internal landing page. Bundled as a single installable ZIP.', 'FILE', '/downloads/chrome-extension/Extension-Mila-Suite.zip', 'manual', 'cat-chrome-extension', '🌸', '1.0.0', 0, 0, 0, '2026-07-16T20:25:38.872Z', '2026-07-16T20:25:38.872Z');
INSERT OR IGNORE INTO Resource (id, workspaceId, title, description, sourceType, fileUrl, provider, categoryId, iconEmoji, currentVersion, isFavorite, openCount, downloadCount, createdAt, updatedAt) VALUES ('cmrnykxnx000rc8uq2xt3nlbf', 'default-workspace', 'Mila 1 — Highlighter Pro with Dashboard', 'Premium chat word highlighter with floating dashboard. Supports custom group names, colors, auto-response templates, and SLA notification controls. Tampermonkey UserScript for LiveChat.', 'FILE', '/downloads/script/Mila-1-Highlighter-Pro.user.js', 'manual', 'cat-script', '🎨', '2025-10-07', 0, 0, 0, '2026-07-16T20:25:38.925Z', '2026-07-16T20:25:38.925Z');
INSERT OR IGNORE INTO Resource (id, workspaceId, title, description, sourceType, fileUrl, provider, categoryId, iconEmoji, currentVersion, isFavorite, openCount, downloadCount, createdAt, updatedAt) VALUES ('cmrnykxou000yc8uqkcrlljb4', 'default-workspace', 'Mila 2 — Duplicate Message Danger Alert', 'Real-time duplicate message detection and spam protection for LiveChat. Highlights duplicate messages with bold red HUD warnings and visual alerts. Tampermonkey UserScript.', 'FILE', '/downloads/script/Mila-2-Duplicate-Checker.user.js', 'manual', 'cat-script', '🚨', '2025-01-21', 0, 0, 0, '2026-07-16T20:25:38.959Z', '2026-07-16T20:25:38.959Z');
INSERT OR IGNORE INTO Resource (id, workspaceId, title, description, sourceType, fileUrl, provider, categoryId, iconEmoji, currentVersion, isFavorite, openCount, downloadCount, createdAt, updatedAt) VALUES ('cmrnykxpu0015c8uqmye6mk6i', 'default-workspace', 'Mila 3 — Minimal UI + SLA Tracker', 'Custom LiveChat UI modifications with heartbeat SLA indicators (yellow/red), rainbow tags, toast notifications, and fixed sidebar widths. Per-ID toggle support. Tampermonkey UserScript.', 'FILE', '/downloads/script/Mila-3-UI-SLA-Tracker.user.js', 'manual', 'cat-script', '⏱️', '2.0.4', 0, 0, 0, '2026-07-16T20:25:38.994Z', '2026-07-16T20:25:38.994Z');
INSERT OR IGNORE INTO Resource (id, workspaceId, title, description, sourceType, fileUrl, provider, categoryId, iconEmoji, currentVersion, isFavorite, openCount, downloadCount, createdAt, updatedAt) VALUES ('cmrnykxqw001cc8uqa2zaxlqb', 'default-workspace', 'Mila 4 — Pengecekan Duration Timer', 'Tracks agent task-checking duration with multi-phase alerts (2min/3min/5min). Auto-starts on trigger keywords, auto-stops on archived chats. Integrates with Mila 1 dashboard settings. Tampermonkey UserScript.', 'FILE', '/downloads/script/Mila-4-Duration-Timer.user.js', 'manual', 'cat-script', '🔍', '1.3.0', 0, 0, 0, '2026-07-16T20:25:39.032Z', '2026-07-16T20:25:39.032Z');
INSERT OR IGNORE INTO Resource (id, workspaceId, title, description, sourceType, fileUrl, provider, categoryId, iconEmoji, currentVersion, isFavorite, openCount, downloadCount, createdAt, updatedAt) VALUES ('cmrnykxs4001jc8uqme9ja4rx', 'default-workspace', 'Kode PGsoft Picker OCR', 'Drag-to-select image region OCR tool using Tesseract.js. Allows agents to visually select a region on an image, perform optical character recognition, and copy the result. Tampermonkey UserScript.', 'FILE', '/downloads/script/Kode-PGsoft-Picker-OCR.user.js', 'manual', 'cat-script', '📷', '2026-06-20', 0, 0, 0, '2026-07-16T20:25:39.076Z', '2026-07-16T20:25:39.076Z');
INSERT OR IGNORE INTO Resource (id, workspaceId, title, description, sourceType, fileUrl, provider, categoryId, iconEmoji, currentVersion, isFavorite, openCount, downloadCount, createdAt, updatedAt) VALUES ('cmrnykxtp001qc8uqii7lasnv', 'default-workspace', 'Bear Decoration Asset', 'Cute bear illustration used as a floating decorative element in the Mila suite interface. PNG format with transparency.', 'FILE', '/downloads/assets/bear.png', 'manual', 'cat-assets', '🐻', '1.0.0', 0, 0, 0, '2026-07-16T20:25:39.134Z', '2026-07-16T20:25:39.134Z');
INSERT OR IGNORE INTO Resource (id, workspaceId, title, description, sourceType, fileUrl, provider, categoryId, iconEmoji, currentVersion, isFavorite, openCount, downloadCount, createdAt, updatedAt) VALUES ('cmrnykxug001xc8uq6eqn646v', 'default-workspace', 'Flower Decoration Asset', 'Pink flower illustration used as a floating decorative element in the Mila suite interface. PNG format.', 'FILE', '/downloads/assets/flower.png', 'manual', 'cat-assets', '🌸', '1.0.0', 0, 0, 0, '2026-07-16T20:25:39.161Z', '2026-07-16T20:25:39.161Z');
INSERT OR IGNORE INTO Resource (id, workspaceId, title, description, sourceType, fileUrl, provider, categoryId, iconEmoji, currentVersion, isFavorite, openCount, downloadCount, createdAt, updatedAt) VALUES ('cmrnykxv90024c8uqrwgabak1', 'default-workspace', 'Mila Sticker Character', 'Mila character sticker illustration used as a mascot/branding element in the Highlighter Pro Suite landing page. PNG format.', 'FILE', '/downloads/assets/mila_sticker.png', 'manual', 'cat-assets', '💖', '1.0.0', 0, 0, 0, '2026-07-16T20:25:39.190Z', '2026-07-16T20:25:39.190Z');
INSERT OR IGNORE INTO Resource (id, workspaceId, title, description, sourceType, fileUrl, provider, categoryId, iconEmoji, currentVersion, isFavorite, openCount, downloadCount, createdAt, updatedAt) VALUES ('cmrnykxvu002bc8uqr3jyi8n9', 'default-workspace', 'Flower Old Decoration Asset', 'Previous version of the flower decoration illustration. PNG format. Kept as a reference/archive asset.', 'FILE', '/downloads/assets/flower_old.png', 'manual', 'cat-assets', '🌺', '1.0.0', 0, 0, 0, '2026-07-16T20:25:39.210Z', '2026-07-16T20:25:39.210Z');
INSERT OR IGNORE INTO Tag (id, name) VALUES ('cmrnykxi50000c8uq1t2k5obq', 'chrome');
INSERT OR IGNORE INTO Tag (id, name) VALUES ('cmrnykxig0001c8uqwqgrklsw', 'password');
INSERT OR IGNORE INTO Tag (id, name) VALUES ('cmrnykxir0002c8uq1cse6vhi', 'livechat');
INSERT OR IGNORE INTO Tag (id, name) VALUES ('cmrnykxj10003c8uqi5gf0lp5', 'productivity');
INSERT OR IGNORE INTO Tag (id, name) VALUES ('cmrnykxjb0004c8uqwh49deho', 'pink');
INSERT OR IGNORE INTO Tag (id, name) VALUES ('cmrnykxk00008c8uqjmt7yyl2', 'automation');
INSERT OR IGNORE INTO Tag (id, name) VALUES ('cmrnykxkg000ac8uqsuevngig', 'advanced');
INSERT OR IGNORE INTO Tag (id, name) VALUES ('cmrnykxkq000bc8uqtzksr67y', 'tool');
INSERT OR IGNORE INTO Tag (id, name) VALUES ('cmrnykxld000fc8uqk08j7sla', 'mila');
INSERT OR IGNORE INTO Tag (id, name) VALUES ('cmrnykxlo000gc8uq2csa2yt9', 'suite');
INSERT OR IGNORE INTO Tag (id, name) VALUES ('cmrnykxm0000ic8uq3syvf701', 'highlighter');
INSERT OR IGNORE INTO Tag (id, name) VALUES ('cmrnykxn0000lc8uqrlbupxh7', 'userscript');
INSERT OR IGNORE INTO Tag (id, name) VALUES ('cmrnykxnb000mc8uqmnd08evd', 'tampermonkey');
INSERT OR IGNORE INTO Tag (id, name) VALUES ('cmrnykxnm000pc8uq2gftkfef', 'dashboard');
INSERT OR IGNORE INTO Tag (id, name) VALUES ('cmrnykxo9000vc8uqa0hst2ex', 'spam');
INSERT OR IGNORE INTO Tag (id, name) VALUES ('cmrnykxoj000wc8uqj20g5r0p', 'duplicate');
INSERT OR IGNORE INTO Tag (id, name) VALUES ('cmrnykxp70012c8uqz5h87r7i', 'sla');
INSERT OR IGNORE INTO Tag (id, name) VALUES ('cmrnykxpi0013c8uqtx88lmyw', 'ui');
INSERT OR IGNORE INTO Tag (id, name) VALUES ('cmrnykxq90019c8uqqklteo1j', 'timer');
INSERT OR IGNORE INTO Tag (id, name) VALUES ('cmrnykxqk001ac8uqtlq3l0aa', 'duration');
INSERT OR IGNORE INTO Tag (id, name) VALUES ('cmrnykxr8001fc8uqu1suzgey', 'ocr');
INSERT OR IGNORE INTO Tag (id, name) VALUES ('cmrnykxrj001gc8uqueaskbc6', 'tesseract');
INSERT OR IGNORE INTO Tag (id, name) VALUES ('cmrnykxrt001hc8uqedns9beh', 'image');
INSERT OR IGNORE INTO Tag (id, name) VALUES ('cmrnykxsh001lc8uqt8z83cvg', 'decoration');
INSERT OR IGNORE INTO Tag (id, name) VALUES ('cmrnykxss001mc8uqmqkz6x4v', 'bear');
INSERT OR IGNORE INTO Tag (id, name) VALUES ('cmrnykxt3001nc8uq64w2ddrv', 'cute');
INSERT OR IGNORE INTO Tag (id, name) VALUES ('cmrnykxtf001oc8uqjtd5me53', 'png');
INSERT OR IGNORE INTO Tag (id, name) VALUES ('cmrnykxu4001tc8uquxk6u33h', 'flower');
INSERT OR IGNORE INTO Tag (id, name) VALUES ('cmrnykxuq001zc8uqzqmihkh3', 'sticker');
INSERT OR IGNORE INTO Tag (id, name) VALUES ('cmrnykxv10021c8uqz7od7rm3', 'mascot');
INSERT OR IGNORE INTO Tag (id, name) VALUES ('cmrnykxvi0028c8uqgq97y278', 'archive');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxjo0006c8uqh526g4no', 'cmrnykxi50000c8uq1t2k5obq');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxjo0006c8uqh526g4no', 'cmrnykxig0001c8uqwqgrklsw');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxjo0006c8uqh526g4no', 'cmrnykxir0002c8uq1cse6vhi');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxjo0006c8uqh526g4no', 'cmrnykxj10003c8uqi5gf0lp5');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxjo0006c8uqh526g4no', 'cmrnykxjb0004c8uqwh49deho');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxl1000dc8uq4682i5h1', 'cmrnykxi50000c8uq1t2k5obq');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxl1000dc8uq4682i5h1', 'cmrnykxk00008c8uqjmt7yyl2');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxl1000dc8uq4682i5h1', 'cmrnykxir0002c8uq1cse6vhi');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxl1000dc8uq4682i5h1', 'cmrnykxkg000ac8uqsuevngig');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxl1000dc8uq4682i5h1', 'cmrnykxkq000bc8uqtzksr67y');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxmg000kc8uqysx1s9aq', 'cmrnykxi50000c8uq1t2k5obq');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxmg000kc8uqysx1s9aq', 'cmrnykxld000fc8uqk08j7sla');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxmg000kc8uqysx1s9aq', 'cmrnykxlo000gc8uq2csa2yt9');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxmg000kc8uqysx1s9aq', 'cmrnykxir0002c8uq1cse6vhi');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxmg000kc8uqysx1s9aq', 'cmrnykxm0000ic8uq3syvf701');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxnx000rc8uq2xt3nlbf', 'cmrnykxn0000lc8uqrlbupxh7');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxnx000rc8uq2xt3nlbf', 'cmrnykxnb000mc8uqmnd08evd');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxnx000rc8uq2xt3nlbf', 'cmrnykxir0002c8uq1cse6vhi');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxnx000rc8uq2xt3nlbf', 'cmrnykxm0000ic8uq3syvf701');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxnx000rc8uq2xt3nlbf', 'cmrnykxnm000pc8uq2gftkfef');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxou000yc8uqkcrlljb4', 'cmrnykxn0000lc8uqrlbupxh7');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxou000yc8uqkcrlljb4', 'cmrnykxnb000mc8uqmnd08evd');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxou000yc8uqkcrlljb4', 'cmrnykxir0002c8uq1cse6vhi');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxou000yc8uqkcrlljb4', 'cmrnykxo9000vc8uqa0hst2ex');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxou000yc8uqkcrlljb4', 'cmrnykxoj000wc8uqj20g5r0p');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxpu0015c8uqmye6mk6i', 'cmrnykxn0000lc8uqrlbupxh7');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxpu0015c8uqmye6mk6i', 'cmrnykxnb000mc8uqmnd08evd');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxpu0015c8uqmye6mk6i', 'cmrnykxir0002c8uq1cse6vhi');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxpu0015c8uqmye6mk6i', 'cmrnykxp70012c8uqz5h87r7i');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxpu0015c8uqmye6mk6i', 'cmrnykxpi0013c8uqtx88lmyw');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxqw001cc8uqa2zaxlqb', 'cmrnykxn0000lc8uqrlbupxh7');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxqw001cc8uqa2zaxlqb', 'cmrnykxnb000mc8uqmnd08evd');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxqw001cc8uqa2zaxlqb', 'cmrnykxir0002c8uq1cse6vhi');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxqw001cc8uqa2zaxlqb', 'cmrnykxq90019c8uqqklteo1j');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxqw001cc8uqa2zaxlqb', 'cmrnykxqk001ac8uqtlq3l0aa');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxs4001jc8uqme9ja4rx', 'cmrnykxn0000lc8uqrlbupxh7');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxs4001jc8uqme9ja4rx', 'cmrnykxnb000mc8uqmnd08evd');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxs4001jc8uqme9ja4rx', 'cmrnykxr8001fc8uqu1suzgey');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxs4001jc8uqme9ja4rx', 'cmrnykxrj001gc8uqueaskbc6');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxs4001jc8uqme9ja4rx', 'cmrnykxrt001hc8uqedns9beh');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxtp001qc8uqii7lasnv', 'cmrnykxrt001hc8uqedns9beh');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxtp001qc8uqii7lasnv', 'cmrnykxsh001lc8uqt8z83cvg');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxtp001qc8uqii7lasnv', 'cmrnykxss001mc8uqmqkz6x4v');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxtp001qc8uqii7lasnv', 'cmrnykxt3001nc8uq64w2ddrv');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxtp001qc8uqii7lasnv', 'cmrnykxtf001oc8uqjtd5me53');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxug001xc8uq6eqn646v', 'cmrnykxrt001hc8uqedns9beh');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxug001xc8uq6eqn646v', 'cmrnykxsh001lc8uqt8z83cvg');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxug001xc8uq6eqn646v', 'cmrnykxu4001tc8uquxk6u33h');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxug001xc8uq6eqn646v', 'cmrnykxjb0004c8uqwh49deho');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxug001xc8uq6eqn646v', 'cmrnykxtf001oc8uqjtd5me53');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxv90024c8uqrwgabak1', 'cmrnykxrt001hc8uqedns9beh');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxv90024c8uqrwgabak1', 'cmrnykxuq001zc8uqzqmihkh3');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxv90024c8uqrwgabak1', 'cmrnykxld000fc8uqk08j7sla');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxv90024c8uqrwgabak1', 'cmrnykxv10021c8uqz7od7rm3');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxv90024c8uqrwgabak1', 'cmrnykxtf001oc8uqjtd5me53');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxvu002bc8uqr3jyi8n9', 'cmrnykxrt001hc8uqedns9beh');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxvu002bc8uqr3jyi8n9', 'cmrnykxsh001lc8uqt8z83cvg');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxvu002bc8uqr3jyi8n9', 'cmrnykxu4001tc8uquxk6u33h');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxvu002bc8uqr3jyi8n9', 'cmrnykxvi0028c8uqgq97y278');
INSERT OR IGNORE INTO ResourceTag (resourceId, tagId) VALUES ('cmrnykxvu002bc8uqr3jyi8n9', 'cmrnykxtf001oc8uqjtd5me53');
